# Generated by Django 5.0.2 on 2024-03-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_options_alter_product_count_and_more'),
        ('main', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
    ]
